import"./assets/modulepreload-polyfill-3cfb730f.js";/* empty css                     */import{a as E,S as w,i as a}from"./assets/vendor-a94593f8.js";class _{constructor(){this.searchQuery="",this.page=1,this.PER_PAGE=40}async fetchGallery(){const t={method:"get",url:"https://pixabay.com/api/",params:{key:"34523545-f21683fd59bfc3e4e2549fe07",q:`${this.searchQuery}`,image_type:"photo",orientation:"horizontal",safesearch:!0,page:`${this.page}`,per_page:`${this.PER_PAGE}`}};try{return(await E(t)).data}catch(s){console.error(s)}}incrementPage(){this.page+=1}resetPage(){this.page=1}resetEndOfHits(){this.endOfHits=!1}get query(){return this.searchQuery}set query(t){this.searchQuery=t}}let v=new w(".photo-card a",{captions:!0,captionsData:"alt",captionDelay:250});const S=document.getElementById("search-button"),h=document.querySelector(".gallery"),n=document.querySelector("#search-bar"),i=document.querySelector(".btn__load-more");let o=0;const r=new _;let c=!0;S.addEventListener("click",p);n.addEventListener("keydown",function(e){e.key==="Enter"&&(e.preventDefault(),p()),c=!0});function p(){const e=n.value.trim();if(h.innerHTML="",r.query=e,r.resetPage(),e===""){O("Please, fill the main field");return}n.value="",o=0,f()}async function f(){try{const e=await r.fetchGallery(),{hits:t,totalHits:s}=e;if(!t.length){u("Sorry, there are no images matching your search query. Please try again.");return}c&&o<s&&($(`Hooray! We found ${s} images !!!`),c=!1,i.classList.remove("is-hidden")),k(t),o+=t.length,o>=s&&(i.classList.add("is-hidden"),P("You've reached the end of search results."))}catch(e){console.error("Error fetching gallery:",e),u("An error occurred while fetching the gallery.")}}function k(e){const t=e.map(({webformatURL:s,largeImageURL:l,tags:d,likes:g,views:m,comments:y,downloads:b})=>`
      <div class="photo-card">
        <a href="${l}">
          <img class="photo-img" src="${s}" alt="${d}" loading="lazy" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b><span class="info__span">${g}</span></p>
          <p class="info-item"><b>Views</b><span class="info__span">${m}</span></p>
          <p class="info-item"><b>Comments</b><span class="info__span">${y}</span></p>
          <p class="info-item"><b>Downloads</b><span class="info__span">${b}</span></p>
        </div>
      </div>`).join("");h.insertAdjacentHTML("beforeend",t),v.refresh()}i.addEventListener("click",()=>{r.incrementPage(),f()});function O(e){a.warning({title:"Warning",message:e,position:"topRight",color:"yellow",timeout:2e3,closeOnEscape:!0,closeOnClick:!0})}function u(e){a.error({title:"Error",message:e,position:"topRight",color:"red",timeout:2e3,closeOnEscape:!0,closeOnClick:!0})}function $(e){a.success({title:"Success",message:e,position:"topRight",color:"green",timeout:2e3,closeOnEscape:!0,closeOnClick:!0})}function P(e){a.info({title:"Info",message:e,position:"topRight",color:"blue",timeout:2e3,closeOnEscape:!0,closeOnClick:!0})}
//# sourceMappingURL=commonHelpers3.js.map
